(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
(* Chimera: Chiral Measures Research Assistant *)
(* \[Copyright] Emilio Pisanty, 2024 *)

(* For more information, see https://github.com/????/???? *)

(*TODO - update this*)


(* ::Input::Initialization:: *)
BeginPackage["Chimera`"];


(* ::Input::Initialization:: *)
$ChimeraVersion::usage="$ChimeraVersion prints the current version of the Chimera package in use and its timestamp.";
$ChimeraTimestamp::usage="$ChimeraTimestamp prints the timestamp of the current version of the Chimera package.";
Begin["`Private`"];
$ChimeraVersion:="Chimera v0.1, "<>$ChimeraTimestamp;
End[];


(* ::Input::Initialization:: *)
$ChimeraDirectory::usage="$ChimeraDirectory is the directory where the current Chimera package instance is located.";


(* ::Input::Initialization:: *)
Begin["`Private`"];
With[{softLinkTestString=StringSplit[StringJoin[ReadList["! ls -la "<>StringReplace[$InputFileName,{" "->"\\ "}],String]]," -> "]},
If[Length[softLinkTestString]>1,(*Testing in case $InputFileName is a soft link to the actual directory.*)
$ChimeraDirectory=StringReplace[DirectoryName[softLinkTestString[[2]]],{" "->"\\ "}],
$ChimeraDirectory=StringReplace[DirectoryName[$InputFileName],{" "->"\\ "}];
]];
End[];


(* ::Input::Initialization:: *)
$ChimeraCommit::usage="$ChimeraCommit returns the git commit log at the location of the Chimera package if there is one.";
$ChimeraCommit::OS="$ChimeraCommit has only been tested on Linux.";


(* ::Input::Initialization:: *)
Begin["`Private`"];
$ChimeraCommit:=(If[$OperatingSystem!="Unix",Message[$ChimeraCommit::OS]];
StringJoin[Riffle[ReadList["!cd "<>$ChimeraDirectory<>" && git log -1",String],{"\n"}]]);
End[];


(* ::Input::Initialization:: *)
Begin["`Private`"];$ChimeraTimestamp="Sat 22 Jun 2024 17:17:00";End[];


(* ::Input::Initialization:: *)
SampleFunction::usage="This is a sample function for the Chimera template.";
Begin["`Private`"];
SampleFunction[x___]:="You have evaluated the Chimera sample function, SampleFunction, on the input "<>ToString[x]
End[];


(* ::Input::Initialization:: *)
EndPackage[];


(* ::Input::Initialization:: *)
DistributeDefinitions["Chimera`"];
